### PR TITLE
MIT license

### PR DESCRIPTION
**Pull request by igeligel**
Add the MIT license and update package.json with proper linking.

It would be also nice to publish a version 1.5.1 with the updated license, so I can use the package.

### CODE REVIEW

**Comment by eXeDK** [comment]
I'll @freeall decide if this is the license he wants to use

**Comment by igeligel** [comment]
@eXeDK He agreed on this already: https://github.com/freeall/currency-codes/issues/3 but a license file was never published. I am doing this here now to be compliant with other systems.

**Comment by eXeDK** [comment]
Fair enough :-) I didn't see #3.

**Comment by igeligel** [comment]
Would be really nice if you could release version 1.5.1 of this package. But this can take time. Thanks for the merge :)

**Comment by eXeDK** [comment]
I'm not sure I have the rights to release packages. We can try and ping @freeall again :-)

**Pull request merged**
